# Generated by Django 5.0.3 on 2025-05-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
