# Generated by Django 5.0.3 on 2025-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
